title: FormSG User Guide
remote_theme: opendocsg/opendoc-theme@master
timezone: Asia/Singapore
repository: opendocsg/opendoc-formsg-faq
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
offline: false
google_analytics: UA-113717369-13
order: #----> Optional, order of documents

styling_options:
  primary_brand_color: '#2f60ce'
  logo_path: /assets/logo-horizontal-color.svg
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: https://go.gov.sg/formsg-support

hide_toolbar:
  sidebar: false
  pdf: false
  github: true

folders:
  - name: '/'
    title: 'FormSG User Guide'
    subtitle: ''
    order:
      - "BasicGuide.md"
      - "AdvancedGuide.md"
      - "WhatsNew.md"
      - "AskAPro.md"

